const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopApi", {
  getAuthStatus: () => ipcRenderer.invoke("auth:get-status"),
  registerAdmin: (payload) => ipcRenderer.invoke("auth:register", payload),
  loginAdmin: (payload) => ipcRenderer.invoke("auth:login", payload),
  renewAdmin: (payload) => ipcRenderer.invoke("auth:renew", payload),
  notifyLoggedIn: () => ipcRenderer.send("auth:logged-in"),
  logout: () => ipcRenderer.invoke("auth:logout"),
  logoutAdmin: () => ipcRenderer.invoke("auth:logout"),
  getLicenseStatus: () => ipcRenderer.invoke("license:get-status"),
  generateLicense: () => ipcRenderer.invoke("license:generate"),
  activateLicense: (payload) => ipcRenderer.invoke("license:activate", payload),
  openWhiteLabelDashboard: () => ipcRenderer.invoke("app:open-white-label-dashboard"),
  openPlatformClientsDashboard: () => ipcRenderer.invoke("app:open-platform-clients-dashboard"),
  checkForUpdates: () => ipcRenderer.invoke("app:check-updates"),
  getUpdateState: () => ipcRenderer.invoke("app:get-update-state"),
  getMasterLiveState: () => ipcRenderer.invoke("app:get-master-live-state"),
  getDefaultApiUrl: () => ipcRenderer.invoke("app:get-default-api-url"),
  downloadUpdate: () => ipcRenderer.invoke("app:download-update"),
  installUpdate: () => ipcRenderer.invoke("app:install-update"),
  getBootstrap: () => ipcRenderer.invoke("app:get-bootstrap"),
  saveProvider: (provider) => ipcRenderer.invoke("providers:save", provider),
  deleteProvider: (providerId) => ipcRenderer.invoke("providers:delete", providerId),
  activateProvider: (providerId) => ipcRenderer.invoke("providers:activate", providerId),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  connectApiEndpoint: (payload) => ipcRenderer.invoke("settings:api-connect", payload),
  disconnectApiEndpoint: (payload) => ipcRenderer.invoke("settings:api-disconnect", payload),
  testApiEndpoint: (payload) => ipcRenderer.invoke("settings:api-test", payload),
  fetchRuntimeStatus: () => ipcRenderer.invoke("backend:runtime-status"),
  fetchBackupStatus: () => ipcRenderer.invoke("backup:status"),
  runBackupNow: () => ipcRenderer.invoke("backup:run"),
  restoreBackup: (archivePath) => ipcRenderer.invoke("backup:restore", archivePath),
  tenantLogin: (payload) => ipcRenderer.invoke("backend:tenant-login", payload),
  fetchTenantProfile: () => ipcRenderer.invoke("backend:tenant-profile"),
  fetchTenants: () => ipcRenderer.invoke("backend:tenant-list"),
  saveTenant: (payload) => ipcRenderer.invoke("backend:tenant-save", payload),
  fetchBranding: () => ipcRenderer.invoke("backend:branding-get"),
  saveBranding: (payload) => ipcRenderer.invoke("backend:branding-save", payload),
  fetchSetupStatus: () => ipcRenderer.invoke("backend:setup-status"),
  completeSetup: () => ipcRenderer.invoke("backend:setup-complete"),
  validateDeviceBinding: () => ipcRenderer.invoke("backend:validate-device"),
  syncActiveProvider: (providerId) => ipcRenderer.invoke("backend:sync-active-provider", providerId),
  fetchActiveProviders: () => ipcRenderer.invoke("backend:active-providers"),
  fetchStreams: (providerId) => ipcRenderer.invoke("backend:fetch-streams", providerId),
  fetchApprovedStreams: () => ipcRenderer.invoke("backend:fetch-approved"),
  fetchUsers: () => ipcRenderer.invoke("backend:fetch-users"),
  fetchOnlineUsers: () => ipcRenderer.invoke("backend:fetch-online-users"),
  fetchAnalyticsLive: () => ipcRenderer.invoke("backend:analytics-live"),
  fetchAnalyticsStreams: () => ipcRenderer.invoke("backend:analytics-streams"),
  fetchTopMatches: () => ipcRenderer.invoke("backend:analytics-top-matches"),
  fetchTopCompetitions: () => ipcRenderer.invoke("backend:analytics-top-competitions"),
  fetchDailyViewers: () => ipcRenderer.invoke("backend:analytics-daily-viewers"),
  fetchCountries: () => ipcRenderer.invoke("backend:analytics-countries"),
  fetchWhiteLabelInstalls: () => ipcRenderer.invoke("backend:white-label-installs"),
  fetchWhiteLabelSubscriptions: () => ipcRenderer.invoke("backend:white-label-subscriptions"),
  createMobileBuild: () => ipcRenderer.invoke("backend:mobile-build"),
  cancelMobileBuild: (buildId) => ipcRenderer.invoke("backend:mobile-build-cancel", buildId),
  fetchMobileBuildStatus: (buildId) => ipcRenderer.invoke("backend:mobile-build-status", buildId),
  fetchMobileBuildHistory: () => ipcRenderer.invoke("backend:mobile-build-history"),
  downloadMobileBuild: (payload) => ipcRenderer.invoke("backend:mobile-build-download", payload),
  fetchApkVersions: () => ipcRenderer.invoke("backend:apk-versions"),
  uploadApk: (payload) => ipcRenderer.invoke("backend:upload-apk", payload),
  setLatestApk: (payload) => ipcRenderer.invoke("backend:set-latest-apk", payload),
  fetchLatestUpdateMeta: () => ipcRenderer.invoke("backend:updates-latest"),
  fetchUpdateHistory: () => ipcRenderer.invoke("backend:updates-history"),
  publishSystemUpdate: (payload) => ipcRenderer.invoke("backend:updates-publish", payload),
  fetchPlatformClients: () => ipcRenderer.invoke("backend:platform-clients"),
  blockPlatformClient: (adminId) => ipcRenderer.invoke("backend:platform-client-block", adminId),
  unblockPlatformClient: (adminId) => ipcRenderer.invoke("backend:platform-client-unblock", adminId),
  extendPlatformClientTrial: (payload) => ipcRenderer.invoke("backend:platform-client-extend-trial", payload),
  resetPlatformClientServer: (adminId) => ipcRenderer.invoke("backend:platform-client-reset-server", adminId),
  deletePlatformClient: (adminId) => ipcRenderer.invoke("backend:platform-client-delete", adminId),
  uploadBrandingAsset: (payload) => ipcRenderer.invoke("backend:branding-upload", payload),
  fetchSecurityDashboard: () => ipcRenderer.invoke("backend:security-dashboard"),
  blockUser: (payload) => ipcRenderer.invoke("backend:block-user", payload),
  unblockUser: (payload) => ipcRenderer.invoke("backend:unblock-user", payload),
  grantFreeAccess: (payload) => ipcRenderer.invoke("backend:free-user", payload),
  removeFreeAccess: (payload) => ipcRenderer.invoke("backend:remove-free-user", payload),
  extendUser: (payload) => ipcRenderer.invoke("backend:extend-user", payload),
  extendSubscription: (payload) => ipcRenderer.invoke("backend:extend-subscription", payload),
  renameUser: (payload) => ipcRenderer.invoke("backend:rename-user", payload),
  restoreUserName: (payload) => ipcRenderer.invoke("backend:restore-user-name", payload),
  resetDevice: (payload) => ipcRenderer.invoke("backend:reset-device", payload),
  setVpnPolicy: (payload) => ipcRenderer.invoke("backend:set-vpn-policy", payload),
  updateFootballItem: (payload) => ipcRenderer.invoke("backend:update-football-item", payload),
  deleteFootballItem: (payload) => ipcRenderer.invoke("backend:delete-football-item", payload),
  fetchNations: () => ipcRenderer.invoke("backend:fetch-nations"),
  saveNation: (payload) => ipcRenderer.invoke("backend:save-nation", payload),
  deleteNation: (nationId) => ipcRenderer.invoke("backend:delete-nation", nationId),
  fetchCompetitions: (nationId) => ipcRenderer.invoke("backend:fetch-competitions", nationId),
  saveCompetition: (payload) => ipcRenderer.invoke("backend:save-competition", payload),
  deleteCompetition: (competitionId) => ipcRenderer.invoke("backend:delete-competition", competitionId),
  fetchClubs: (payload) => ipcRenderer.invoke("backend:fetch-clubs", payload),
  saveClub: (payload) => ipcRenderer.invoke("backend:save-club", payload),
  deleteClub: (clubId) => ipcRenderer.invoke("backend:delete-club", clubId),
  uploadAsset: (payload) => ipcRenderer.invoke("backend:upload-asset", payload),
  approveStream: (payload) => ipcRenderer.invoke("backend:approve-stream", payload),
  removeApprovedStream: (streamId) => ipcRenderer.invoke("backend:remove-approved", streamId),
  onMenuAction: (callback) => {
    const listener = (_, payload) => callback(payload);
    ipcRenderer.on("menu:action", listener);
    return () => ipcRenderer.removeListener("menu:action", listener);
  },
  onUpdateState: (callback) => {
    const listener = (_, payload) => callback(payload);
    ipcRenderer.on("update:state", listener);
    return () => ipcRenderer.removeListener("update:state", listener);
  },
  onMasterLiveState: (callback) => {
    const listener = (_, payload) => callback(payload);
    ipcRenderer.on("master-live:state", listener);
    return () => ipcRenderer.removeListener("master-live:state", listener);
  },
});
